### ISSUE TITLE
update fillme notebook

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/workshops#11]
the fillme notebook needs to be updated to included the updates from https://github.com/popsim-consortium/workshops/pull/10

https://github.com/popsim-consortium/workshops/blob/main/intro_stdpopsim/Intro_stdpopsim_fillme.ipynb

@gtsambos ?

**Comment by gtsambos** [comment]
In my session I'm going to strongly encourage them to not use the fill me
notebook, but will update it after the workshop

**Comment by agladstein** [comment]
I don't know how many people used it in my workshop, but there were some comments that people liked it. So, I do think some people might like to use it. But, if nobody has time to update before your workshop, that's okay.
I might be able to get to it, but not too likely.
